[package]
name = "atty"
version = "0.1.0"
authors = ["softprops <d.tangren@gmail.com>"]
description = "A simple interface for querying atty."
documentation = "http://softprops.github.io/atty"
homepage = "https://github.com/softprops/atty"
repository = "https://github.com/softprops/atty"
keywords = ["terminal", "tty"]
license = "MIT"

[dependencies]
libc = "0.1"